import styles from "../styles/Home.module.scss";

import type { NextPage } from "next";
import { useContext, useEffect, useState } from "react";
import { getProducts } from "../helpers/dataFetchers";

import Head from "next/head";
import ErrorComp from "../components/ErrorComp/ErrorComp";
import Loading from "../components/Loading/Loading";
import { AppContext } from "../context/app-state";

const Home: NextPage = () => {
  const context = useContext(AppContext);
  const { error, setError, loading, setLoading, data, setData } = context;

  useEffect(() => {
    setLoading(true);
    getProducts(setData, setError);
    setLoading(false);
  }, [setData, setError, setLoading]);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Audio Station</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {error && <ErrorComp />}
        {loading && <Loading />}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
