import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { getProducts } from "../helpers/getProducts";

const Home: NextPage = () => {
  const [data, setData]: any = useState();

  useEffect(() => {
    getProducts(setData);
  }, [getProducts, setData]);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Shopper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
